#!/usr/bin/with-contenv bash

if [ -f /usr/bin/apt ]; then
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4
    echo "deb https://repo.clickhouse.com/deb/stable/ main/" | tee /etc/apt/sources.list.d/clickhouse.list
    apt-get update
fi
